import re

content = open('index.html', encoding='utf-8').read()

html_replacement = '''<div id="info-ui">
        <div id="big-terminal">
          <div class="big-term-titlebar">
            <div class="big-term-dots">
              <span class="r"></span>
              <span class="y"></span>
              <span class="g"></span>
            </div>
            <div class="big-term-title">overseer — guardian layer</div>
          </div>
          <div class="big-term-body" id="big-term-body">
            <span id="big-term-cursor" class="big-term-cursor"></span>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix i">[system]</span> initializing guardian layer...</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix i">[daemon]</span> attaching to filesystem events on /src</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix g">[active]</span> intercepting agent modifications in real-time</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix i">[audit]</span> detected 400 lines generated by AI agent in 0.2 seconds</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix c">[alert]</span> <strong>CRITICAL VULNERABILITY DETECTED</strong> in auth.js:5</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix c">[reason]</span> hardcoded JWT secret — token can be forged bypass</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix w">[warn]</span> missing rate limits on /api/login endpoint</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix i">[resolve]</span> translating changes to plain English narrations...</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix g">[success]</span> comprehension gap closed. you are fully aware of what was built.</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix i">[sync]</span> committing context to permanent knowledge base</div>
            <div class="big-term-line"><span class="prompt">$</span> <span class="prefix g">[ready]</span> awaiting next human command or agent modification.</div>
          </div>
        </div>
      </div>'''

css_replacement = '''
    #info-ui {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      pointer-events: none;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      opacity: 0;
      transition: opacity 0.5s;
    }

    #info-ui.show {
      opacity: 1;
      pointer-events: all;
    }

    #big-terminal {
      width: 78%;
      max-width: 1100px;
      margin: 0 auto;
      background: rgba(2, 4, 8, 0.4);
      backdrop-filter: blur(24px);
      -webkit-backdrop-filter: blur(24px);
      border: 1px solid rgba(129, 140, 248, 0.4);
      border-radius: 8px;
      box-shadow: 0 32px 80px rgba(0, 0, 0, 0.8), inset 0 1px 0 rgba(255, 255, 255, 0.15);
      overflow: hidden;
      font-family: 'JetBrains Mono', monospace;
      display: flex;
      flex-direction: column;
      min-height: 520px;
    }

    .big-term-titlebar {
      display: flex;
      align-items: center;
      padding: 0.9rem 1.4rem;
      background: rgba(2, 4, 8, 0.8);
      border-bottom: 1px solid rgba(129, 140, 248, 0.2);
      position: relative;
    }

    .big-term-dots {
      display: flex;
      gap: 8px;
      position: absolute;
      left: 1.4rem;
    }

    .big-term-dots span {
      width: 12px;
      height: 12px;
      border-radius: 50%;
    }

    .big-term-dots .r { background: #ff5f56; }
    .big-term-dots .y { background: #ffbd2e; }
    .big-term-dots .g { background: #27c93f; }

    .big-term-title {
      flex: 1;
      text-align: center;
      font-size: 0.8rem;
      color: rgba(255, 255, 255, 0.7);
      letter-spacing: 0.15em;
      font-weight: 500;
    }

    .big-term-body {
      padding: 2rem;
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 1.1rem;
    }
    
    .big-term-line {
      font-size: 0.9rem;
      color: var(--white);
      opacity: 0;
      transform: translateY(12px);
      transition: opacity 0.4s ease, transform 0.4s ease;
      display: none;
      line-height: 1.5;
    }

    .big-term-line .prompt { color: var(--accent-1); margin-right: 0.8rem; font-weight: 700; }
    .big-term-line .prefix { margin-right: 0.8rem; font-weight: 600; text-transform: uppercase; font-size: 0.8rem; letter-spacing: 0.05em; }
    .big-term-line .prefix.i { color: #60a5fa; }
    .big-term-line .prefix.c { color: #ff4444; }
    .big-term-line .prefix.w { color: #f59e0b; }
    .big-term-line .prefix.g { color: #22c55e; }
    
    .big-term-cursor {
      display: inline-block;
      width: 10px;
      height: 1.1em;
      background: var(--accent-1);
      animation: blink 1s step-end infinite;
      vertical-align: middle;
      margin-left: 0.6rem;
    }
</style>'''

js_target = """        cardDefs.forEach(c => { const el = document.getElementById(c.id); if (el) ap >= c.t ? el.classList.add('show') : el.classList.remove('show'); });
        if (ap >= 0.30) { startFeed(); startDpFeed(); } else { stopFeed(); }"""
js_replacement = """        const termLines = document.querySelectorAll('.big-term-line');
        const termCursor = document.getElementById('big-term-cursor');
        const termBody = document.getElementById('big-term-body');
        if (termLines.length > 0 && termCursor && termBody) {
          let lastVisibleIndex = -1;
          const apClamped = Math.max(0, Math.min(1, ap));
          termLines.forEach((line, index) => {
            const threshold = (index + 1) / (termLines.length + 1);
            if (apClamped >= threshold) {
              line.style.display = 'block';
              setTimeout(() => { line.style.opacity = 1; line.style.transform = 'translateY(0)'; }, 10);
              lastVisibleIndex = index;
            } else {
              line.style.display = 'none';
              line.style.opacity = 0;
              line.style.transform = 'translateY(12px)';
            }
          });
          if (lastVisibleIndex >= 0) {
            termLines[lastVisibleIndex].appendChild(termCursor);
          } else {
            termBody.insertBefore(termCursor, termBody.firstChild);
          }
        }"""

# 1. Replace Info-UI HTML
# Matches either the legacy #info-hl structure or the existing #big-terminal structure
html_pattern = re.compile(r'<div id="info-ui">.*?</div>\s*</div>', re.DOTALL)
if '<div id="big-terminal">' in content:
    print('HTML already contains #big-terminal')
    count_html = 0
else:
    content, count_html = html_pattern.subn(html_replacement, content)
    print(f'HTML replacement count: {count_html}')

# 2. Add CSS before </style>
if '#big-terminal {' in content:
    print('CSS for #big-terminal already exists')
else:
    content = content.replace('</style>', css_replacement)
    print('CSS added')

# 3. Replace JS Scroll Logic
if 'const termLines =' in content:
    print('JS already contains termLines logic')
else:
    content = content.replace(js_target, js_replacement)
    print('JS replaced')

open('index.html', 'w', encoding='utf-8').write(content)
